### ISSUE TITLE
Adding plugins to GQIS

### ISSUE THREAD

**Issue by ithacalr** [spatial-data-discovery/spatial-data-discovery.github.io#15]
Can't search for or add plugins to QGIS 3.4 on Mac

**Comment by dt-woods** [comment]
It may be that we have to do some setting up with the software. What method of installation did you use?

**Comment by ithacalr** [comment]
Per my changelog, I installed the longterm stable version from https://qgis.org/en/site/forusers/download.html. It could be that my Mac OS is not current enough -- I use OS Sierra 10.12.6 and the installer that I used is labelled for OS High Sierra (10.13) and newer. There is an alternative build with Mac Installer Packages for macOS El Capitan (10.11) and newer -- I can try that later and tell you how it goes.

**Comment by ithacalr** [comment]
Got it to work and added the QuickMap plugin!
