### ISSUE TITLE
Make image float to the right

### ISSUE THREAD

**Issue by ithacalr** [spatial-data-discovery/spatial-data-discovery.github.io#24]
How do I make my animation float to the right?

**Comment by dt-woods** [comment]
Two things you need to do in your .Rmd file:

1. Change `<div class="video-wrapper">` to `<div class="video-fr-wrapper">`
2. Change `<video id="davisvideo"` to `<video id="rosenvideo"`

In the `styles.css` file in the repository, I have definitions for these two tags. `#rosenvideo` assumes that your video is 500 pixels wide. I don't know your vertical pixel count, which will need to be updated when your video is ready (L108).

Here's what it looked like for mine.

![image-fr-wrapper](https://user-images.githubusercontent.com/29642997/70255439-cd765f00-1754-11ea-9003-48cca6860d60.PNG)
