### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by aehilla** [spatial-data-discovery/spatial-data-discovery.github.io#50]
This script takes .csv files with text data and analyzes the text in each row. It assigns two sentiment scores, assessing subjectivity and polarity. The sentiment scores are added to the .csv as a new column, then the .csv with sentiment scores is exported as a new file.

**Comment by dt-woods** [comment]
Ran on file `american` in our scripts folder assigning column "A." Not a lot there to look at, though "sick" has some negative polarity. I'm not sure how to interpret the results, but it executable without errors :)
