### ISSUE TITLE
Simplified Roulette

### ISSUE THREAD

**Issue by johnhennin** [spatial-data-discovery/spatial-data-discovery.github.io#51]
This script will simulate a simplified version of roulette (simplified in that you can only place color bets or straight bets). Players start with 1000 "dollars" and this value changes as they play and win/lose. Players have the option to choose between No Zero roulette, French or Single Zero roulette, and American or Double Zero roulette.

**Comment by dt-woods** [comment]
Received an uncaught error when betting on my roulette game (see image below). Looks like something's wrong with the if/elif statements on L55-62; it's missing an else to catch whatever is missed by the elif's. 
![roulette](https://user-images.githubusercontent.com/29642997/92667840-0db5cf80-f2db-11ea-8eb3-3f92bf2e1278.png)
