### ISSUE TITLE
Barchart Generator

### ISSUE THREAD

**Issue by sylviashea1** [spatial-data-discovery/spatial-data-discovery.github.io#52]
Takes input .csv, allows user to specify x and y variable from columns. Saves barchart as .png.

**Comment by dt-woods** [comment]
Tested using `leanlow_testfile.csv` with `x=1` and `y=2` producing this doodle:

![Doodle](https://user-images.githubusercontent.com/29642997/92652949-a5a3c100-f2bb-11ea-808c-5eba2d7e73e0.png)

**Comment by dt-woods** [comment]
You may want to caution your users that your script produces a PNG of the same name as the title in the working directory.
