### ISSUE TITLE
file_remover

### ISSUE THREAD

**Issue by kelannen** [spatial-data-discovery/spatial-data-discovery.github.io#57]
This script takes in the path to a directory from which you want to delete all files of a certain type and what that type/extension is (e.g. .py or .ini) and removes all files of that type within that directory.

**Comment by dt-woods** [comment]
A beautiful thing, but you might want to mention the recursive aspect of your search.
![file_remover](https://user-images.githubusercontent.com/29642997/92660792-20bfa400-f2c9-11ea-802d-863329125b68.png)
