### ISSUE TITLE
Rankings Calculator

### ISSUE THREAD

**Issue by XLPeng57** [spatial-data-discovery/spatial-data-discovery.github.io#58]
This scripts uses Python to calculate ranking based on total scores. The users can choose different orders(ascending/descending) and rules(count the average of each player's best 5 scores) they want to apply.

**Comment by dt-woods** [comment]
Hi @XLPeng57, if you have an opportunity, please add an example CSV file to our `/scripts` directory and make a note in the README.md that it can be used with your script.

**Comment by XLPeng57** [comment]
> Hi @XLPeng57, if you have an opportunity, please add an example CSV file to our `/scripts` directory and make a note in the README.md that it can be used with your script.

Hi Professor! I've added a sample test file and pushed it into the /scripts folder.
