### ISSUE TITLE
Emotion Detection

### ISSUE THREAD

**Issue by CSStarfish** [spatial-data-discovery/spatial-data-discovery.github.io#59]
This script uses convolutional neural networks (CNN) to detect a person's emotional state based on their facial expressions in a video stream.  The video source can either be a live-stream from a webcam or a pre-recorded video.

**Comment by dt-woods** [comment]
Seems to run, but there's no training data so the script crashes.

**Comment by CSStarfish** [comment]
Just an update: Since there was the issue with access training data, I changed my utility script to make_art.py.  I submitted that for regrading 28 days ago, and it addresses #60, #46.  Thanks!

**Comment by dt-woods** [comment]
@CSStarfish, got it. Please adjust the argparse to be before the execution of any functions and add a note that this script does not work as a stand-alone Python script in the README and that it should be run in Jupyter notebook environment and re-tag the Regrade issue.

**Comment by CSStarfish** [comment]
Thank you! I fixed the argparse and README.

**Comment by CSStarfish** [comment]
@dt-woods I moved the argparse after the import statements, and it executes before the code, but I just wanted to let you know that the warnings will still show up before the help documentation prints because of the TensorFlow import statements.  Thanks again!
